rust/README.md
rust/notes.md
rust/plan.md

This PR describes a Rust training course called "Practical Networked Applications in Rust", and lays out a draft lesson plan.
[Rendered README](https://github.com/brson/talent-training/tree/master/rust).
[Rendered lesson plan](https://github.com/brson/talent-training/blob/master/rust/plan.md).
The flow of this course is curious, with topics derived from the needs of the hands-on projects and the hands-on projects designed to teach useful and interesting topics, leaving some important topics not covered (at least yet). I believe the lesson plan proceeds quite differently from typical Rust intro/beginner material. I hope that the documentation conveys the rationale sufficiently.
It is not quite finished, but I think there's enough here to understand what it's about, enough to review and …

Create initial readme for Rust course and outline lesson plan

---

rust/projects/tools/project.md

Just a minor fix I forgot to include in an earlier pr.

rustfix -> rustfmt

---

rust/css/text.css
rust/notes.md
rust/projects/file-io/project.md

Fixes https://github.com/pingcap/talent-plan/issues/11

Project 2 description

---

rust/projects/file-io/Cargo.lock
rust/projects/file-io/Cargo.toml
rust/projects/file-io/src/bin/kvs.rs
rust/projects/file-io/src/kv.rs
rust/projects/file-io/tests/tests.rs

Based on #36 .
There should be a lot that can be improved, but I'm expected to hear from you first. @brson  
I don't know how to test the compaction part of this project. For now, this PR includes a random test for correctness, but I think it's not solid. Students should adjust some parameters so that they can test effectively.  As we do not have a clear goal which the compaction should accomplish, the effect of the compaction (saving space) cannot be tested either. Any suggestions on it?

Code and tests for Rust training course Project 2

---

dss/percolator/README.md

This PR adds a README for the Percolator lab.

dss: add a README for the Percolator section

---

rust/projects/tools/project.md

Fix wrong part number in Project 1

---

rust/notes.md
rust/projects/file-io/project.md

This is just committing my own notes about readings. @mapleFu is going to be looking out for articles that support the projects as he works through them. Here are some sources to start from.
cc @mapleFu @sticnarf

Throw in some simple rust readings

---

rust/projects/file-io/src/kv.rs
rust/projects/networking/src/engines/kvs.rs
rust/projects/networking/src/engines/mod.rs

Modify "Error" to "Errors" to keep consistent with std doc

---

rust/projects/file-io/project.md
rust/projects/networking/project.md
rust/projects/tools/project.md

Implementation changes in project 3 are included in #120 
#123 is fixed after #120 and this pr are merged.

Add receiver spec in text

---

.circleci/config.yml
dss/src/kvraft/tests.rs
dss/src/raft/mod.rs

Signed-off-by: Neil Shen <overvenus@gmail.com>

dss: cargo fmt

---

rust/projects/project-3/benches/engine_bench.rs
rust/projects/project-3/src/bin/kvs-server.rs
rust/projects/project-3/src/engines/mod.rs
rust/projects/project-3/src/engines/sled.rs
rust/projects/project-3/src/lib.rs
rust/projects/project-4/src/bin/kvs-server.rs
rust/projects/project-4/src/engines/mod.rs
rust/projects/project-4/src/engines/sled.rs
rust/projects/project-4/src/lib.rs

Rust: Wrap sled::Db with SledKvsEngine

---

rust/projects/project-1/Cargo.toml
rust/projects/project-2/Cargo.toml
rust/projects/project-3/Cargo.toml
rust/projects/project-4/Cargo.toml
rust/projects/project-5/Cargo.toml

Thank you for reviewing the code and giving me so much advice! @brson

Change author of example projects to Yilin

---

rust/projects/project-1/project.md

fix wrong word in project-1/project.md

---

rust/lesson-plan.md

Fix [rs] link error.

---

rust/projects/project-2/project.md

Two misspellings occur in terminology.

fix more typos

---

rust/CONTRIBUTING.md
rust/building-blocks/bb-2.md
rust/building-blocks/bb-4.md

Start with the easier file types then move on to vecs. Make the motivation clearer. Describe the multi-value serialization exercise better.

rust: Clarify bb-2 exercises per feedback

---

rust/CONTRIBUTING.md

Replace "section" with "project". Indicate that subjects are
intentionally revisited multiple times.

rust: expand CONTRIBUTING.md

---

rust/projects/project-2/project.md
rust/projects/project-3/project.md
rust/projects/project-4/project.md
rust/projects/project-5/project.md

[#207](https://github.com/pingcap/talent-plan/issues/207)

Rust: italicise the difference from previous projects

---

rust/projects/project-3/project.md
rust/projects/project-4/project.md

Fix benchmark typos

---

tidb/mapreduce/urltop10_example.go

fix wrong code comments in urltop10_example.go.

TiDB/MR: fix wrong code comments in urltop10_example.go

---

tidb/mapreduce/README.md
tidb/mapreduce/mapreduce.go

Update README and add more comments to make it clearer.

TiDB/MapReduce: update README and add more comments

---

rust/projects/project-4/project.md
rust/projects/project-5/project.md

Document the panic-control dev-dependency in projects 4 and 5.

Document panic-control dev-dependency

---

tidb/join/README.md
tidb/mapreduce/README.md
tidb/mergesort/README.md

Make it more clear of what document should contains.

tidb: update document requirements

---

dss/raft/src/kvraft/server.rs
dss/raft/src/raft/mod.rs

Signed-off-by: Neil Shen <overvenus@gmail.com>

raft: tweak few API

---

dss/raft/README.md
dss/raft/src/kvraft/client.rs
rust/projects/project-2/src/kv.rs
rust/projects/project-3/benches/engine_bench.rs
rust/projects/project-3/src/engines/kvs.rs
rust/projects/project-4/src/engines/kvs.rs
rust/projects/project-5/src/engines/kvs.rs

* Practical Networked Applications in Rust
* Update: `BufReaderWithPos` ~~and `BufWriterWithPos`~~.
* Fix: `Temp_dir` is dropped during the test.
* Distributed Systems in Rust
* Update: README.md
* Fix: wrong code in the comment.

./rust code update and ./dss/raft description update

---

rust/projects/project-2/project.md

rust/project-2: Add KvStore::open from tests

---

rust/projects/project-2/src/error.rs
rust/projects/project-2/src/kv.rs
rust/projects/project-2/tests/tests.rs

project-2: refactor test fn name and refine comments

project-2: add the period to the error comment

---

rust/projects/project-1/src/kv.rs
rust/projects/project-5/src/engines/kvs.rs
rust/projects/project-5/src/engines/mod.rs
rust/projects/project-5/src/engines/sled.rs

Fix clippy lints.

---

rust/projects/project-3/src/bin/kvs-client.rs
rust/projects/project-3/src/bin/kvs-server.rs

Signed-off-by: Rustin-Liu <rustin.liu@gmail.com>

rust(project-3): refactor some code

---

rust/projects/project-4/README.md

Signed-off-by: Muhammad Falak R Wani <falakreyaz@gmail.com>

rust/docs: correct link for rust-three-day-course

---

courses/dss/raft/src/raft/mod.rs

Signed-off-by: koushiro <koushiro.cqx@gmail.com>
Fix some missing update about async code in #339
Tests 
- Manual test
Side effects
- None
- None

dss: fix some missing updates about async code

---

talent-challenge-program/selected-projects.md

Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>
Tests 
- Unit test
- Integration test
- No code
Side effects
- Possible performance regression
- Increased code complexity

talent-challenge-program: update recommended skills

---

courses/dss/linearizability/src/models.rs

- Issue number: close https://github.com/pingcap/talent-plan/issues/356
Fix clippy warning redundant closure .
Tests 
- Unit test

dss: fix redundant closure

---

talent-challenge-program/selected-projects.md

update mentee of project Defining Placement Rules in SQL

---

talent-challenge-program/selected-projects.md

update mentee of project TiCDC Snapshot Level Consistency Replication

update mentee of project TiCDC Snapshot Level Consistency Replication

---

talent-challenge-program/selected-projects.md

This PR update the difficulty to hard.

Update "SQL Statement Level Statistics" to hard

---

courses/dss/raft/src/kvraft/tests.rs
courses/dss/raft/src/raft/tests.rs

Signed-off-by: Riptide3 <riptide.yzy@gmail.com>
When I run `make test_others` to check that things are going right in the raft, there are two places of code denied by clippy. And this PR fix them.
Tests 
Run `make test_others` and all tests passed.

courses/dss/raft: adjust code to pass the new version clippy

---

courses/tp102-how-to-use-git-github.md

-A small format error, a space is redundant in this md.

Markdown format error in courses/tp102-how-to-use-git-github.md

---

talent-challenge-program2021/selected-projects.md

Add TinySQL project
Tests 
- No code

Add TinySQL project

---

talent-challenge-program2021/selected-projects.md

Tests 
- Unit test
- Integration test
- No code
Side effects
- Possible performance regression
- Increased code complexity

update for TCP2021 Sept open

---

talent-challenge-program2021/selected-projects.md

Tests 
- Unit test
- Integration test
- No code
Side effects
- Possible performance regression
- Increased code complexity

add 18745 and change an mentor

---

talent-challenge-program2021/selected-projects.md

Tests 
- Unit test
- Integration test
- No code
Side effects
- Possible performance regression
- Increased code complexity

Add one TCP issue 4095

---

README.md

- Breif description of the problem: 
The previous link is no longer accessible. 
Replace it with the link from [talent-plan/.github/ISSUE_TEMPLATE/question.md](https://github.com/pingcap/talent-plan/blob/master/.github/ISSUE_TEMPLATE/question.md) .
Tests 
- No code

README.md: fix the link error

---

courses/dss/labrpc/src/network.rs
courses/dss/raft/src/kvraft/tests.rs

- Issue number: close #413 
clippy is complaining about we borrowing a reference that is immediately dereferenced
remove the borrowing and pass the reference directly

fix clippy error

---

courses/dss/raft/src/raft/mod.rs

- Issue number: close #446  
- Breif description of the problem: build failed because we bind a function that does not return a value to a `_` field
remove this binding

dss : fix clippy error 
