pingcap/talent-plan

dss/Makefile

The default log level does not work for the misspelled package name. This PR fixes that.

Fix default log level in dss

---

dss/src/raft/config.rs
dss/src/raft/tests.rs

- Fix the previous logical mistake checking the order of index of committed log
- Add the missing `check_one_leader` call in `test_count_2b`
- Rename the `test_figure_82c` to `test_figure_8_2c`

Various fix on the test frameworks in dss

---

dss/README.md

Add a readme for the raft lab and the kvraft lab

dss: Add a readme for the raft lab and the kvraft lab

---

dss/percolator/src/tests.rs

This PR fixes the test can pass even if the internal thread has panicked.

dss: fix test_get_timestamp_under_unreliable_network

---

dss/src/raft/mod.rs

There is a typo in dss/src/raft/mod.rs.

Fix OK() in raft

---

rust/projects/networking/project.md

We are asking students to create a `create_engine` function to create a `KvsEngine` by engine name. 
However, the `create_engine` function inevitably introduces dynamic dispatching, which is not optimal. It's better not to give such an instruction.

Remove the instruction of the `create_engine` function

---

rust/notes.md

I periodicaly receieve requests for access to this, but it is
out of date and useless.

Remove link to old Rust notes

---

dss/percolator/src/tests.rs

clippy::all implies clippy::let-unit-value. This changeset removes the let-binding of a unit value which would cause an error.

dss/percolator: clippy error on let-binding a unit value

---

dss/src/kvraft/tests.rs

Using `unwrap()` for `try_recv()` can cause panic.
This seems to be a mistake, because "recv" is used in similar places：
https://github.com/pingcap/talent-plan/blob/f55dfc48139f1d945af1a8e697bb80fb6733484b/dss/src/kvraft/tests.rs#L286-L296

Fix try_recv() which causes panic

---

rust/projects/networking/benches/engine_bench.rs

Signed-off-by: Yilin Chen <sticnarf@gmail.com>
In project 3, `KvsEngine` methods now need `&mut self`. We changed code and tests only but ignored benches. This PR fixes Project 3 benches.

Rust: Fix bench in Project 3

---

rust/projects/networking/src/engines/kvs.rs

Tiny bug fix of Project 3 code

Rust: Fix uncompacted is not reset after a compaction

---

rust/notes.md
rust/projects/networking/project.md
rust/projects/parallelism/project.html
rust/projects/parallelism/project.md

Fixes https://github.com/pingcap/talent-plan/issues/38
I put this together quickly after our discussion @sticnarf. I do have a few concerns:
- there is apparently no production-quality concurrent map type we can incorporate :-/
- like in the previous project, this abstracts a thing then compares to implementations. I don't know if it is valuable to do the same type of exercise again. I'd prefer if we can find a new angle on this, so I've suggested we do a compile-time abstraction using cargo features, but I'm open to any ideas.

Outline Rust project 4

---

dss/labrpc/src/lib.rs
dss/src/kvraft/tests.rs
dss/src/raft/mod.rs

Missing `dyn` for trait object (bare trait object) is a warning by default now as rust-lang/rust#61203 is merged, which breaks labrpc.
Also fixed a few other warnings and unclear documents.

Fix labrpc building for Rust Nightly

---

rust/CONTRIBUTING.md

Signed-off-by: Yilin Chen <sticnarf@gmail.com>
Static sites are removed in #150, then the content about it in CONTRIBUTING.md can be removed too.

Rust: Remove content about static site in CONTRIBUTING.md

---

README.md
tidb/README.md

Move TiDB course details into its own README.
This adds a description of what's in the repo, brief descriptions of the courses, and links to the individual courses for further information.
I took the liberty of giving titles to the dss and tidb courses: "Distributed Systems in Rust", and "Distributed Systems in Go". This makes at least the titles of the three courses stylistically consistent. You'll note that the changes here push toward being PingCAP-agnostic. I do not want to limit the audience, scaring away potential users and contributors, by appearing to be PingCAP-specific (in the same vein I would prefer to [change the repo name](https://github.com/pingcap/talent-plan/issues/107).
Because I am only familiar with the Rust course, it has the most detailed description. Please do …

Expand top-level README.

---

rust/projects/project-1/Cargo.lock
rust/projects/project-1/Cargo.toml
rust/projects/project-2/Cargo.lock
rust/projects/project-2/Cargo.toml
rust/projects/project-3/Cargo.lock
rust/projects/project-3/Cargo.toml
rust/projects/project-4/Cargo.lock
rust/projects/project-4/Cargo.toml
rust/projects/project-5/Cargo.lock
rust/projects/project-5/Cargo.toml

Signed-off-by: Yilin Chen <sticnarf@gmail.com>
float-cmp yanked its 0.4.1 release. We can remove the FIXME now.

Remove float-cmp FIXMEs

---

README.md

This was conflicting with the [TiDB]: https://github.com/pingcap/tidb link.

Fix Distributed Systems in Go link.

---

tidb/README.md

They were producing an extra /tidb/ in the URL.

Fix broken links in README.md

---

rust/README.md

'langauge' replaced with 'language'

Typo in README

---

dss/labrpc/src/lib.rs

check is the server has been killed before dispatch request to server and before reply to client

labrpc: fix reply to client even server killed

---

rust/projects/project-3/project.md

Working through Project 3 - I think these references to `kvs-client` should be for `kvs-server` instead.

rust: Fix mentions of kvs-client that should be kvs-server

---

rust/projects/project-1/project.md

same as line 377:
- `cargo test --doc` &mdash; test the doc tests in the library

rust: project-1 remove redundant

---

rust/projects/project-2/project.md

I guess there should be an `m` after the `the`.

rust: project2 typo

---

rust/README.md

The original link https://tikv.org/deep-dive/ does not exist anymore, replace with the correct one https://tikv.org/docs/deep-dive/introduction/.
Fix #262 .

Fix broken TiKV deep dive link

---

rust/projects/project-3/project.md

`cargo bench` does not support the `--release` flag. According to the
Cargo book [1]:
> Benchmarks are always built with the bench profile. Binary and lib
> targets are built separately as benchmarks with the bench profile.
> Library targets are built with the release profiles when linked to
> binaries and benchmarks. Dependencies use the release profile.
```bash
$ cargo --version
cargo 1.36.0 (c4fcfb725 2019-05-15)
$ cargo bench --release
error: Found argument '--release' which wasn't expected, or isn't valid
in this context
USAGE:
cargo bench [OPTIONS] [BENCHNAME] [-- <args>...]
For more information try --help
```
[1]
https://doc.rust-lang.org/cargo/commands/cargo-bench.html#cargo-bench

rust/projects/project-3/project.md: Remove --release reference

---

tidb/mapreduce/urltop10_example.go

According to the code in `ExampleURLTop10()` https://github.com/pingcap/talent-plan/blob/adb5ceb3f8a54fbcbc24bbbc010c7a4b297d5a5d/tidb/mapreduce/urltop10_example.go#L15-L30 `ExampleURLTop10Map()` is called in second round instead of first round.

mapreduce: fix ExampleURLTop10Map comment

---

tidb/mapreduce/casegen.go

Both `genUniformCases` and `genPercentCases` will return a slice of
closures.
When generating closures, they bind variable which is out of iteration
scope. for example, `genUniformCases` bind closures with card,
`genPercentCases` will bind closures with p.
It's a common mistake in golang programming.[1]
1. Declare variable within the body of loop.
2. Bind this variable with closure.
1. https://github.com/golang/go/wiki/CommonMistakes
https://github.com/pingcap/talent-plan/issues/254
Reviewed by: Felix Chen

Closures are bound to wrong variable

---

rust/projects/project-4/project.md

Remove `--release` flag to cargo bench as it's not supported.

Remove --release flag to cargo bench

---

dss/Makefile
dss/raft/src/kvraft/client.rs
dss/raft/src/kvraft/config.rs
dss/raft/src/kvraft/server.rs
dss/raft/src/kvraft/tests.rs
dss/raft/src/lib.rs
dss/raft/src/raft/mod.rs
dss/raft/src/raft/persister.rs

Deny unused variables, dead code, and missing doc

raft: deny unused variables, dead code, and missing doc

---

dss/labrpc/src/lib.rs
dss/raft/README.md
dss/rust-toolchain

I ran into a few problems when trying to get the project to build with nightly:
- not all versions support `clippy` and `fmt` https://rust-lang.github.io/rustup-components-history/
- newer versions of `clippy` have additional warnings, which cause previous code to fail
I have found that when using nightly this can all be avoided if you specify a `rust-toolchain` file. The following code compiles/tests pass locally with the specified toolchain (latest with clippy and fmt).

reproducible builds by specifying rustc toolchain

---

rust/CONTRIBUTING.md
rust/docs/lesson-plan.md

The link to join the TiKV's Slack is outdated. Students trying to get
help can get a Slack's error page.
This commit uses the same invite link used on the tikv/tikv project and
updated on tikv/tikv#5530.

Update slack invite link

---

rust/projects/project-4/project.md

rust: Correct threadpoolmessage enum

---

rust/projects/project-4/src/engines/kvs.rs

In KvStore::open(), `readers` is just inserted after initialization, then left there and finally dropped.
We can either delete related codes or use it for constructing KvStoreReader.

rust/project-4: fix dead code in KvStore::open()

---

rust/building-blocks/bb-3.md

BB3's exercise points to Custom Serialization. The exercise consists of
using serde to serialize and deserialize redis protocol messages. For this
purpose it's necessary writing a new serde's data format, making it able to
serialize and deserialize redis protocol's messages.
This commit updates BB3's exercise mentioned above and points the
helping link for serde's documentation about writing a data format.
Discussed on tikv-wg slack on:
- https://tikv-wg.slack.com/archives/CKD9363A8/p1573310455016400
- https://tikv-wg.slack.com/archives/CKD9363A8/p1574274353032000

rust/building-blocks: change BB3's exercise helping link on serde docs

---

courses/dss/raft/README.md

This [commit](https://github.com/pingcap/talent-plan/commit/4c74c3653fd4bb3388138e2d4260a44dc9f2a131) update all dependencies but the corresponding doc links in `courses/dss/README.md` are still old.
I update all old version dependencies links to the latest in `courses/dss/README.md`.(Version codes same as `Cargo.toml`)
Tests 
- No code

dss: Update to latest dependencies doc links

---

courses/rust/docs/lesson-plan.md

Current links point to old `master/rust` subdirectories which have been recently changed to `master/courses/rust`.

courses/rust: Update subdirectories links

---

talent-challenge-program/selected-projects.md

Add Chaos Mesh project to talent challenge program. 
This pr adds three tasks for Chaos Mesh project: 
* Support using plugins to extend scheduler   
* Support injecting HTTP fault
* Support injecting fault into Java appliations and JVM

Add Chaos mesh project to talent challenge program

---

courses/dss/labrpc/src/network.rs

In `courses/dss/labrpc/src/network.rs`, it use `Duration::from_secs` to delay the unreliable RPC, which cause RPC too later to start, so can't pass any unreliable test in 2C
Change `Duration::from_secs` to `Duration::from_millis`

courses/dss/raft: fix wrong Duration used in RPC Delay

---

courses/rust/projects/project-3/Cargo.lock
courses/rust/projects/project-3/Cargo.toml
courses/rust/projects/project-3/benches/engine_bench.rs
courses/rust/projects/project-3/src/bin/kvs-server.rs
courses/rust/projects/project-3/src/engines/sled.rs
courses/rust/projects/project-3/src/lib.rs
courses/rust/projects/project-3/src/server.rs
courses/rust/projects/project-4/Cargo.lock
courses/rust/projects/project-4/Cargo.toml
courses/rust/projects/project-4/src/bin/kvs-server.rs
courses/rust/projects/project-4/src/engines/kvs.rs
courses/rust/projects/project-4/src/engines/sled.rs
courses/rust/projects/project-4/src/lib.rs
courses/rust/projects/project-4/src/server.rs
courses/rust/projects/project-4/src/thread_pool/shared_queue.rs

When I finished the project3, I checked the solution in the repository. But I found that the solution could not pass the test. 
Running `cargo run --bin kvs-server -- --engine sled` and `cargo bench` would cause error with message: ` panicked at 'attempted to leave type nodrop::NoDrop<(epoch::Epoch, garbage::Bag)>  uninitialized, which is invalid' `.
I found that this may be caused by a low version of crate in the repository that is not compatible with the new version of rust.
I have tried both `stable rustc 1.49.0 (e1884a8e3 2020-12-29)` and `nightly rustc 1.51.0-nightly (b12290861 2021-01-29)`.
I update the version of `criterion` to "0.3" and `sled` to "0.34.6". Then I replaced the deprecated methods in code(including the use of `extern crate`) both …

courses/rust/projects/project-[3-4]: fix errors due to crate compatibility

---

courses/rust/projects/project-2/src/bin/kvs.rs

Previously used `.expect()` calls would never be called. Since given arguments are defined as required, `clap` gives us a guarantee that code inside of `match` branches will not be called unless all required arguments are given by user.
`.expect()` calls are changed to `.unwrap()` calls.
As it's a documented behavior of `clap` library as far as I understand there is no need to cover such case with tests.

Using 'unwrap()' instead of 'expect("msg")'
